// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'linkItem': string;
  'navbarItems': string;
}
export const cssExports: CssExports;
export default cssExports;
